### PR TITLE
feat: Set HostURL from env variable if creds.HostURL is empty 

### PR DESCRIPTION
**Pull request by hikhvar**
### Description of your changes

Use the default `IONOS_API_URL` if the creds.HostURL is empty but the variable is set. This allows to overwrite the IONOS API endpoint on a provider level additionally to "per-resource".

So the precedence is:
1. creds.HostURL
2. value of variable IONOS_API_URL set for the provider
3. The default https://api.ionos.com/

This PR adds:

## Checklist

I have:

- [x] Add PR name as appropriate (e.g. `feat`/`fix`/`doc`/`test`/`refactor`)
- [x] Run `make reviewable` to ensure this PR is ready for review
- [x] Add or update tests
- [x] Add or update Documentation
- [x] Update CHANGELOG.md (label: `upcoming release`)
- [x] Check Sonar Cloud Scan
- [ ] Update Github or Jira Issue

### CODE REVIEW

**Comment by amoga-ionos** [comment]
Hello, @hikhvar 

Overwriting the endpoint is supported in Crossplane Provider using Kubernetes Secret, just like _credentials_, according with the Crossplane guidelines. Why should we support environment variable in this case? I am a little bit confused of adding this feature.

Furthermore, adding this kind of support should include as well the credentials for the IONOS Cloud account and be documented, from my point of view.

Looking forward for your answer in order to discuss this approach within our team,
Ana

_Note_: it is recommended to follow the checklist when opening a PR, to make sure we keep a consistent commits history and the PR is ready to be reviewed.

**Comment by hikhvar** [comment]
I know it supports the setup via secret. However, we generate the secrets and crossplane resources by a system (lets call it A) getting the credentials injected by the clients. Our system A talks to a staging API of IONOS. System A and the client of it doesn't know they are running in staging, so it would be very convenient for us only configuring the IONOS API in the crossplane pod via an environment variable as a global default for all resources

**Comment by hikhvar** [comment]
FYI: Running `make reviewable` will add the two lines

```

---
```

To every crd yaml file. Those are removed again by `make crds.clean`....

**Comment by hikhvar** [comment]
FYI: Your SonarCloud configuration expect test coverage for test code itself. Thats very hard to achieve.

**Comment by amoga-ionos** [comment]
Hello, @hikhvar 

Thank you for the explanations and updates. This PR will be merged and included into the next release.

**Review by amoga-ionos — APPROVED** [review]

**Pull request merged**
